airddm/urls.py
# coding: utf-8

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('website.urls', namespace='website')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

url(r'^admin/password_reset/$', auth_views.password_reset, name='admin_password_reset'),
url(r'^admin/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

# static files (images, css, javascript, etc.)

website/urls.py
# coding: utf-8

from django.conf.urls import url
from views import IndexView, ArticleView, TeaserView, ArticleRedirectView, ContactFormView, TemplateView, CategorieView


app_name = 'website'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^ajax/contact/$', ContactFormView.as_view(), name='contact'),
    url(r'^article/(?P<pk>[0-9]+)/$', ArticleRedirectView.as_view(), name='article-redirect'),
    url(r'^article/(?P<slug>[-\w]+)/$', ArticleRedirectView.as_view(), name='article-redirect'),
    url(r'^article/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', ArticleView.as_view(), name='article'),
    url(r'^categories/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', CategorieView.as_view(), name='categories'),
    url(r'^client9/$', TemplateView.as_view(template_name="clients/client1.html"), name="client1"),
    url(r'^client2/$', TemplateView.as_view(template_name="clients/client2.html"), name="client2"),
    url(r'^client3/$', TemplateView.as_view(template_name="clients/client3.html"), name="client3"),
    url(r'^client4/$', TemplateView.as_view(template_name="clients/client4.html"), name="client4"),
    url(r'^client5/$', TemplateView.as_view(template_name="clients/client5.html"), name="client5"),
    url(r'^client6/$', TemplateView.as_view(template_name="clients/client6.html"), name="client6"),
    url(r'^client7/$', TemplateView.as_view(template_name="clients/client7.html"), name="client7"),
    url(r'^client8/$', TemplateView.as_view(template_name="clients/client8.html"), name="client8"),
    url(r'^client9/$', TemplateView.as_view(template_name="clients/client9.html"), name="client9"),
    url(r'^teaser$', TeaserView.as_view(), name='launch'),
]

website/models.py
# coding: utf-8
from PIL import Image
import os
import shutil

from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

from django.conf import settings

# Create your models here.


class Categorie(models.Model):
    categories_text = models.CharField(max_length=200)
    short_description = models.CharField(max_length=200, blank=True)
    slug = models.SlugField(max_length=200)

    def __str__(self):
        return self.categories_text

    class Meta:
        verbose_name = ('Catégorie')
        verbose_name_plural = ('Catégories')

    def save(self):
        self.slug = slugify(self.categories_text)
        super(Categorie, self).save()


def upload_path(obj, filename):
    extension = filename[filename.rfind("."):]
    filename = filename[:filename.find(extension)]
    return 'illustration/{0}{1}'.format(slugify(filename), extension)


class Article(models.Model):
    categories = models.ManyToManyField(Categorie, blank=False)
    title = models.CharField(max_length=200, blank=False)
    subtitle = models.CharField(max_length=200, blank=False)
    text = RichTextUploadingField("Article Text", blank=False)
    img_illustration = models.ImageField(upload_to=upload_path, default='illustration/no_image.png')
    pub_date = models.DateTimeField('date published', blank=False)
    slug = models.SlugField(max_length=200)
    author = models.ForeignKey(User)

    def get_or_create_thumbnail(self):
        path = settings.MEDIA_ROOT + 'illustration/'
        img_name = self.img_illustration.name
        extension = img_name[img_name.rfind("."):]
        img_name = img_name[:img_name.find(extension)]
        filename = img_name[img_name.rfind("/") + 1:]
        if not os.path.exists(path + filename + "_thumbnail.path"):
            size = 400, 300
            thumbnail = Image.open(self.img_illustration)
            thumbnail.thumbnail(size)
            thumbnail.save(path + filename + "_thumbnail" + extension)
            thumbnail_path = path + filename + "_thumbnail" + extension
            return thumbnail_path

#    def move_img_illustration(self):
#       if not os.path.exists(settings.MEDIA_ROOT + 'illustration/{0}'.format(str(self.pk))):
#          os.mkdir(settings.MEDIA_ROOT + 'illustration/{0}'.format(str(self.pk)))
#       img_name = self.img_illustration.name
#       img_path = self.img_illustration.path
#       if not os.path.isfile(img_name):
#           img_name = img_name[img_name.rfind("/") + 1:]
#           new_path = settings.MEDIA_ROOT + 'illustration/{0}/{1}'.format(str(self.pk), img_name)
#           shutil.move(img_path, new_path)
#           self.img_illustration = new_path
#           self.save()
#       else:
#           return True

    def save(self):
        self.slug = slugify(self.title)
        super(Article, self).save()
        self.get_or_create_thumbnail()
        # self.move_img_illustration()

    class Meta:
        verbose_name = ('Article')
        verbose_name_plural = ('Articles')

website/forms.py
# coding: utf-8

from django import forms
from localflavor.fr.forms import FRPhoneNumberField
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class ContactForm(forms.Form):
    full_name = forms.CharField(label='Your full name *', max_length=100, required=True)
    email = forms.EmailField(label='Your email *', max_length=100, required=True)
    company = forms.CharField(label='Your company *', max_length=100, required=True)
    phone_number = FRPhoneNumberField(label='Your phone number *', required=True)
    role = forms.CharField(label='Your role *', max_length=100, required=True)
    message = forms.CharField(label='Your message *', widget=forms.Textarea, required=True)


class CurriculumForm(forms.Form):
    first_name = forms.CharField(label='Your first name *', max_length=100, required=True)
    last_name = forms.CharField(label='Your last name *', max_length=100, required=True)
    email_cv = forms.EmailField(label='Your email *', max_length=100, required=True)
    phone_number_cv = FRPhoneNumberField(label='Your phone number *', required=True)
    curriculum = forms.FileField(label='Your curriculum vitae *')

    def clean_curriculum(self):
        curriculum = self.cleaned_data['curriculum']
        curriculum_type = curriculum.content_type.split('/')[1]
        print curriculum_type.lower()
        if curriculum_type.lower() in settings.CONTENT_TYPES:
            if curriculum._size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_(u'La taille de votre fichier ne doit pas dépasser %s. Taille actuelle : %s ') % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(curriculum._size)))
        else:
            raise forms.ValidationError(_(u'Extension de fichier non supportée'))
        return curriculum

website/views.py
# coding: utf-8

from django.views.generic import TemplateView, DetailView, RedirectView, FormView, ListView
from django.views.generic.edit import FormMixin
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib import messages

from forms import ContactForm, CurriculumForm
from models import Article, Categorie

from website.emails import contact_us, contact_us_copy, curriculum_cv, curriculum_cv_copy


# Create your views here.
class ContactFormView(FormView):
    form_class = ContactForm
    success_message = "Nous avons bien pris en compte votre message et nous vous répondrons dans les plus brefs délais."
    success_url = "/#contact"

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        full_name = form.cleaned_data['full_name']
        email = form.cleaned_data['email']
        company = form.cleaned_data['company']
        role = form.cleaned_data['role']
        message = form.cleaned_data['message']
        phone_number = form.cleaned_data['phone_number']
        contact_us(full_name, email, company, role, phone_number, message)
        contact_us_copy(email)
        response = HttpResponseRedirect(self.get_success_url())
        if self.request.is_ajax():
            data = {
                'success_message': self.success_message,
            }
            return JsonResponse(data)
        else:
            return response

    def form_invalid(self, form):
        response = HttpResponseRedirect(self.get_success_url())
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response


class IndexView(FormMixin, ListView):
    '''
    HomePage
    '''
    model = Article
    template_name = 'website/homepage/index.html'
    queryset = Article.objects.all().order_by('id')
    success_url = "/#contact"
    form_class = CurriculumForm

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, 'candidature validée')
        return self.success_url

    def form_valid(self, form):
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        email_cv = form.cleaned_data['email_cv']
        phone_number_cv = form.cleaned_data['phone_number_cv']
        curriculum = self.request.FILES['curriculum']
        curriculum_cv(first_name, last_name, email_cv, phone_number_cv, curriculum)
        curriculum_cv_copy(email_cv)
        return super(IndexView, self).form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def post(self, request, *args, **kwargs):
        super(IndexView, self).get(request, *args, **kwargs)
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['first_form'] = ContactForm()
        context['snd_form'] = CurriculumForm()
        return context


class ArticleRedirectView(RedirectView):
    model = Article

    def get_redirect_url(self, *args, **kwargs):
        if 'pk' in kwargs.keys():
            article = get_object_or_404(Article, pk=kwargs['pk'])
        else:
            article = get_object_or_404(Article, slug=kwargs['slug'])
        return reverse('website:article', kwargs={'pk': article.pk, 'slug': article.slug})


class ArticleView(DetailView):
    model = Article
    template_name = 'website/blog/article.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleView, self).get_context_data(*args, **kwargs)
        context['articles'] = Article.objects.all()
        context['categorie'] = Categorie.objects.all()
        return context


class TeaserView(TemplateView):
    '''
    Teaser
    '''
    template_name = 'website/teaser/index.html'


class CategorieView(DetailView):
    model = Categorie
    template_name = 'website/blog/categorie.html'

    def get_context_data(self, *args, **kwargs):
        context = super(CategorieView, self).get_context_data(*args, **kwargs)
        current_category = context['categorie']
        context['current_articles'] = current_category.article_set.all()
        context['articles'] = Article.objects.all()
        context['all_categorie'] = Categorie.objects.all()
        return context

website/templates/website/blog/article.html
{% extends 'website/layouts/__base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% block index %}{% url 'website:index' %}{%endblock%}
{% block content %}
        <div class="c-layout-page">
            <div class="c-content-box c-size-md">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9">
                            <div class="c-content-blog-post-1-view">
                                <div class="c-content-blog-post-1">
                                    <div class="c-media">
                                        <img class="c-photo img-responsive center-block" src="{{article.img_illustration.url}}" alt="">
                                    </div>
                                    <div class="c-title c-font-bold c-font-uppercase">
                                        <a href="#">{{ article.title }}</a>
                                    </div>
                                    <div class="c-panel c-margin-b-30">
                                        <div class="c-author">
                                            <a href="">Par
                                                <span class="c-font-uppercase">{{article.author.username}}</span>
                                            </a>
                                        </div>
                                        <div class="c-date">le
                                            <span class="c-font-uppercase">{{article.pub_date|date:"l j F Y"}}</span>
                                        </div>
                                        <ul class="c-tags c-theme-ul-bg">
                                            {% for category in article.categories.all %}
                                                <li>{{category}}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="c-desc">
                                        {{article.text|safe}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <!-- BEGIN: CONTENT/BLOG/BLOG-SIDEBAR-1 -->
                            <!-- <form action="#" method="post">
                                <div class="input-group">
                                    <input type="text" class="form-control c-square c-theme-border" placeholder="Search blog...">
                                    <span class="input-group-btn">
                                        <button class="btn c-theme-btn c-theme-border c-btn-square" type="button">Go!</button>
                                    </span>
                                </div>
                            </form> -->
                            <div class="c-content-ver-nav">
                                <div class="c-content-title-1 c-theme c-title-md c-margin-t-40">
                                    <h3 class="c-font-bold c-font-uppercase">Articles</h3>
                                    <div class="c-line-left c-theme-bg"></div>
                                </div>
                                <ul class="c-menu c-arrow-dot1 c-theme">
                                {% for article in articles %}
                                    <li>
                                        <a href="{% url 'website:article' article.id article.slug %}">{{ article.title }}</a>
                                    </li>
                                {% endfor %}
                                </ul>
                                <div class="c-content-title-1 c-theme c-title-md c-margin-t-40">
                                    <h3 class="c-font-bold c-font-uppercase">Categories</h3>
                                    <div class="c-line-left c-theme-bg"></div>
                                </div>
                                <ul class="c-menu c-arrow-dot1 c-theme">
                               {% for category in categorie %}
                                    <li><a href="{% url 'website:categories'  category.pk category.slug %}" style="text-transform:capitalize">{{category}}</a></li>
                                {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END: BLOG LISTING  -->
            <!-- END: PAGE CONTENT -->
        </div>
        {% endblock %}
        {% block extrajs %}
                <script src="{% static 'js/scripts/pages/lightbox-gallery.js' %}" type="text/javascript"></script>
        {% endblock %}

website/templates/website/blog/categorie.html
{% extends 'website/layouts/__base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% block extrahead %}
{% endblock %}
{% block index %}{% url 'website:index' %}{%endblock%}
{% block content %}
        <div class="c-layout-page">
            <div class="c-content-box c-size-md">
                <div class="container">
                    <div id="filters-container" class="cbp-l-filters-text">
                        <div class="cbp-l-filters-text-sort">Voir les catégories:</div>
                        <div data-filter="*" class="cbp-filter-item"> Toutes
                            <div class="cbp-filter-counter"></div>
                        </div> /
                        {% for category in all_categorie %}
                        <div data-filter=".{{category.slug}}" class="cbp-filter-item {% if categorie == category %}cbp-filter-item-active{% endif %} "> {{category}}
                            <div class="cbp-filter-counter"></div>
                        </div> /
                        {% endfor %}
                    </div>
                    <div id="grid-container" class="cbp cbp-l-grid-agency">
                    {% for article in current_articles %}
                        <div class="cbp-item {% for category in article.categories.all %}{{category.slug}} {% endfor %}">
                            <a href="{% url 'website:article' article.id article.slug %}" >
                                <div class="cbp-caption">
                                    <div class="cbp-caption-defaultWrap">
                                        <img src="{{article.img_illustration.url}}" alt=""> </div>
                                </div>
                                <div class="cbp-l-grid-agency-title">{{article.title}}</div>
                                <div class="cbp-l-grid-agency-desc">{{article.subtitle}}</div>
                            </a>
                        </div>
                    {% endfor %}
                    {% for article in articles %}
                    {% if article not in current_articles %}
                        <div class="cbp-item cbp-item-off {% for category in article.categories.all %}{{category.slug}} {% endfor %}">
                            <a href="{% url 'website:article' article.id article.slug %}" >
                                <div class="cbp-caption">
                                    <div class="cbp-caption-defaultWrap">
                                        <img src="{{article.img_illustration.url}}" alt=""> </div>
                                </div>
                                <div class="cbp-l-grid-agency-title">{{article.title}}</div>
                                <div class="cbp-l-grid-agency-desc">{{article.subtitle}}</div>
                            </a>
                        </div>
                    {% endif %}
                    {% endfor %}
                    </div>
                </div>
            </div>
            <!-- END: PAGE CONTENT -->
        </div>

    {% endblock %}
    {% block extrajs %}
        <script type="text/javascript">
       (function($, window, document, undefined) {
    'use strict';

    // init cubeportfolio
    $('#grid-container').cubeportfolio({
        filters: '#filters-container',
        loadMore: '#loadMore-container',
        loadMoreAction: 'click',
        layoutMode: 'grid',
        defaultFilter: '.{{categorie.slug}}',
        animationType: 'slideLeft',
        gapHorizontal: 35,
        gapVertical: 15,
        gridAdjustment: 'responsive',
        mediaQueries: [{
            width: 1400,
            cols: 5
        }, {
            width: 1100,
            cols: 4
        }, {
            width: 800,
            cols: 3
        }, {
            width: 500,
            cols: 2
        }, {
            width: 320,
            cols: 1
        }],
        caption: 'zoom',
        displayType: 'lazyLoading',
        displayTypeSpeed: 100,
    });

})(jQuery, window, document);
        </script>
    {% endblock %}